name: Release Pipeline
on:
  push:
    branches: [main]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Release
        run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
